import { StyleSheet } from 'react-native';
import { cardShadowStyle } from '../../../../components/business-detail/styles';
import { C } from '../constants';

export const styles = StyleSheet.create({
  formCard: {
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    ...cardShadowStyle,
  } as object,
  anonNotice: {
    marginBottom: 16,
    backgroundColor: 'rgba(125,155,118,0.08)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(125,155,118,0.20)',
    padding: 12,
    gap: 4,
  },
  anonTitle: { fontSize: 14, fontWeight: '700', color: C.charcoal },
  anonBody: { fontSize: 13, fontWeight: '500', color: C.charcoal60 },
  formHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingHorizontal: 4,
    paddingTop: 0,
    marginBottom: 8,
  },
  formHeaderText: { flex: 1, gap: 4 },
  formHeaderTitle: { fontSize: 20, fontWeight: '700', color: C.charcoal },
  formHeaderSub: { fontSize: 14, color: C.charcoal60 },
  prefillLabel: { fontSize: 12, color: C.charcoal60, paddingHorizontal: 4, marginBottom: 8 },
  section: { paddingVertical: 20 },
  fieldHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  fieldHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  fieldLabel: { fontSize: 16, fontWeight: '600', color: C.charcoal },
  fieldOptional: { fontSize: 14, fontWeight: '400', color: 'rgba(45,45,45,0.45)' },
  titleInput: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 999,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.60)',
    paddingHorizontal: 20,
    paddingVertical: 16,
    fontSize: 15,
    fontWeight: '600',
    color: C.charcoal,
  },
  bodyInput: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.60)',
    paddingHorizontal: 20,
    paddingVertical: 16,
    fontSize: 15,
    fontWeight: '500',
    color: C.charcoal,
    minHeight: 120,
    lineHeight: 22,
  },
  progressRow: { marginTop: 8 },
  progressTrack: {
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.15)',
    overflow: 'hidden',
  },
  progressFill: { height: 4, borderRadius: 2, backgroundColor: 'rgba(114,47,55,0.60)' },
  charCount: { fontSize: 12, color: 'rgba(45,45,45,0.45)', textAlign: 'right', marginTop: 4 },
  charCountWarn: { color: '#E88D67' },
  minCharsHint: { fontSize: 12, color: C.coral, marginTop: 8, paddingHorizontal: 4 },
  photosRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  photoThumb: { width: 80, height: 80, borderRadius: 10, overflow: 'hidden', position: 'relative' },
  photoImg: { width: 80, height: 80 },
  photoRemoveBtn: {
    position: 'absolute',
    top: 4,
    right: 4,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: C.coral,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoPickerZone: {
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: 'rgba(45,45,45,0.20)',
    borderRadius: 12,
    paddingVertical: 24,
    paddingHorizontal: 16,
    alignItems: 'center',
    gap: 8,
    backgroundColor: C.charcoal10,
    marginTop: 12,
  },
  photoPickerIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(45,45,45,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  photoPickerLabel: { fontSize: 15, fontWeight: '600', color: C.charcoal60 },
  photoPickerSub: { fontSize: 13, fontWeight: '400', color: 'rgba(45,45,45,0.45)' },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    padding: 16,
    borderRadius: 12,
    backgroundColor: C.errorBg,
    borderWidth: 1,
    borderColor: C.errorBorder,
    marginTop: 24,
  },
  errorText: { flex: 1, fontSize: 14, fontWeight: '500', color: C.coral, lineHeight: 20 },
  submitWrap: { marginTop: 32, gap: 12, alignItems: 'center' },
  submitBtn: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
    borderRadius: 999,
    minHeight: 56,
  },
  submitBtnBusy: { opacity: 0.92 },
  submitBtnDisabled: { backgroundColor: C.charcoal10 },
  submitText: { fontSize: 16, fontWeight: '700', color: C.white },
  submitTextDisabled: { color: C.charcoal60 },
  invalidHint: { fontSize: 13, color: 'rgba(45,45,45,0.45)', textAlign: 'center' },
});
