import { StyleSheet } from 'react-native';
import { businessDetailSpacing, businessDetailColors } from '../../../components/business-detail/styles';
import { CARD_BG_COLOR, NAVBAR_BG_COLOR } from '../../../styles/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: businessDetailColors.page,
  },
  stickyHeader: {
    paddingHorizontal: businessDetailSpacing.pageGutter,
    paddingTop: 14,
    paddingBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 8,
    zIndex: 50,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 32,
  },
  hero: {
    paddingHorizontal: businessDetailSpacing.pageGutter,
    paddingTop: 28,
    paddingBottom: 28,
    alignItems: 'center',
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: businessDetailColors.charcoal,
    textAlign: 'center',
    letterSpacing: -0.5,
    marginBottom: 8,
  },
  heroSub: {
    fontSize: 14,
    lineHeight: 20,
    color: businessDetailColors.textMuted,
    textAlign: 'center',
    maxWidth: 320,
  },
  tabContainer: {
    paddingHorizontal: businessDetailSpacing.pageGutter,
    marginBottom: 12,
    alignItems: 'center',
  },
  tabRow: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.80)',
    borderRadius: 999,
    borderWidth: 2,
    borderColor: 'rgba(45,45,45,0.20)',
    padding: 4,
    gap: 4,
  },
  tab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
  },
  tabActive: {
    backgroundColor: NAVBAR_BG_COLOR,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 3,
  },
  tabText: {
    fontSize: 13,
    fontWeight: '600',
    color: businessDetailColors.textMuted,
  },
  tabTextActive: {
    color: '#fff',
  },
  card: {
    marginHorizontal: businessDetailSpacing.pageGutter,
    backgroundColor: CARD_BG_COLOR,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.20)',
    padding: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.10,
    shadowRadius: 6,
    elevation: 4,
    overflow: 'hidden',
  },
  list: {
    gap: 8,
    marginTop: 16,
  },
  expandBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 16,
    alignSelf: 'center',
    backgroundColor: CARD_BG_COLOR,
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: CARD_BG_COLOR,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.16,
    shadowRadius: 10,
    elevation: 4,
  },
  expandText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#fff',
  },
  skeletonWrap: {
    gap: 8,
    paddingVertical: 8,
  },
  skeletonRow: {
    minHeight: 72,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  skeletonLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  skeletonBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  skeletonAvatar: {
    width: 48,
    height: 48,
    borderRadius: 8,
  },
  skeletonIdentity: {
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  skeletonName: {
    width: '62%',
    height: 13,
    borderRadius: 7,
  },
  skeletonSub: {
    width: '38%',
    height: 10,
    borderRadius: 6,
  },
  skeletonRight: {
    alignItems: 'flex-end',
    gap: 6,
    marginLeft: 8,
  },
  skeletonPill: {
    width: 58,
    height: 20,
    borderRadius: 999,
  },
  skeletonTiny: {
    width: 52,
    height: 10,
    borderRadius: 6,
  },
  emptyWrap: {
    alignItems: 'center',
    paddingVertical: 32,
    gap: 12,
  },
  emptyIcon: {
    width: 64,
    height: 64,
    borderRadius: 12,
    backgroundColor: businessDetailColors.page,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    fontSize: 14,
    color: businessDetailColors.textMuted,
    textAlign: 'center',
    maxWidth: 260,
    lineHeight: 20,
  },
  retryBtn: {
    backgroundColor: CARD_BG_COLOR,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    marginTop: 4,
  },
  retryText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fff',
  },
  badgeSection: {
    marginTop: 20,
    marginHorizontal: businessDetailSpacing.pageGutter,
    backgroundColor: businessDetailColors.coral,
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    gap: 4,
  },
  badgeSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
  },
  badgeSectionSub: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.65)',
    textAlign: 'center',
    marginBottom: 12,
  },
  badgeBtns: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  badgePrimaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 999,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 4,
    elevation: 2,
  },
  badgePrimaryText: {
    fontSize: 13,
    fontWeight: '600',
    color: businessDetailColors.coral,
  },
  badgeSecondaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 999,
  },
  badgeSecondaryText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fff',
  },
});
