import { StyleSheet } from 'react-native';
import { businessDetailColors } from '../../../components/business-detail/styles';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    flex: 1,
    marginBottom: 8,
  },
  unavailableWrap: {
    flex: 1,
    marginBottom: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(114,47,55,0.16)',
    backgroundColor: '#F3F5F8',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    gap: 8,
  },
  unavailableIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(114,47,55,0.12)',
  },
  unavailableTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#2D2D2D',
    textAlign: 'center',
  },
  unavailableText: {
    fontSize: 13,
    lineHeight: 18,
    color: 'rgba(45,45,45,0.65)',
    textAlign: 'center',
  },
  pinMarkerWrap: {
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinMarkerWrapSelected: {
    width: 26,
    height: 26,
  },
  pinAura: {
    position: 'absolute',
    width: 16,
    height: 16,
    borderRadius: 999,
    backgroundColor: 'rgba(114,47,55,0.22)',
  },
  pinAuraSelected: {
    width: 22,
    height: 22,
    backgroundColor: 'rgba(114,47,55,0.32)',
  },
  pin: {
    width: 20,
    height: 20,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 2,
    backgroundColor: businessDetailColors.coral,
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
    transform: [{ rotate: '-45deg' }],
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinSelected: {
    width: 26,
    height: 26,
    borderTopLeftRadius: 13,
    borderTopRightRadius: 13,
    borderBottomLeftRadius: 13,
    borderBottomRightRadius: 2,
    borderWidth: 2,
    shadowColor: '#722F37',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 4,
  },
  pinCore: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    transform: [{ rotate: '45deg' }],
  },
  clusterWrap: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  clusterOuter: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(114,47,55,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  clusterInner: {
    minWidth: 30,
    height: 30,
    borderRadius: 15,
    paddingHorizontal: 8,
    backgroundColor: businessDetailColors.coral,
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  clusterText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  userLocationMarker: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  userLocationDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: businessDetailColors.coral,
    borderWidth: 2.5,
    borderColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 3,
  },
});

export const calloutStyles = StyleSheet.create({
  dismissZone: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '100%',
  },
  card: {
    position: 'absolute',
    bottom: 24,
    left: 16,
    right: 16,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.10,
    shadowRadius: 16,
    elevation: 8,
    overflow: 'hidden',
  },
  inner: {
    padding: 16,
    gap: 12,
  },
  handleBar: {
    width: 36,
    height: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(45,45,45,0.15)',
    alignSelf: 'center',
    marginBottom: 4,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  info: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  name: {
    fontSize: 17,
    fontWeight: '700',
    color: '#2D2D2D',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 4,
  },
  stars: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1,
  },
  ratingText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#2D2D2D',
  },
  reviewsText: {
    fontSize: 12,
    color: 'rgba(45,45,45,0.55)',
  },
  dot: {
    width: 3,
    height: 3,
    borderRadius: 999,
    backgroundColor: 'rgba(45,45,45,0.30)',
  },
  category: {
    fontSize: 13,
    color: 'rgba(45,45,45,0.60)',
    flexShrink: 1,
  },
  address: {
    fontSize: 12,
    color: 'rgba(45,45,45,0.50)',
  },
  viewBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#722F37',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    flexShrink: 0,
  },
  viewBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
});
