import { StyleSheet } from 'react-native';
import { ONBOARDING_TOKENS } from '../../../components/onboarding/onboardingTheme';

export const styles = StyleSheet.create({
  errorBanner: {
    backgroundColor: 'rgba(229,224,229,0.95)',
    borderColor: 'rgba(114,47,55,0.35)',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginBottom: 16,
  },
  errorText: {
    color: ONBOARDING_TOKENS.coral,
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
    fontWeight: '600',
  },
  counterWrap: {
    alignItems: 'center',
    marginBottom: 16,
  },
  counterPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: 'rgba(157,171,155,0.2)',
    backgroundColor: 'rgba(157,171,155,0.10)',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  counterPillReady: {
    borderColor: 'rgba(157,171,155,0.3)',
    backgroundColor: 'rgba(157,171,155,0.14)',
  },
  counterText: {
    color: ONBOARDING_TOKENS.sage,
    fontSize: 14,
    fontWeight: '600',
  },
  counterHint: {
    marginTop: 8,
    fontSize: 13,
    lineHeight: 18,
    color: ONBOARDING_TOKENS.charcoal60,
    fontWeight: '600',
    textAlign: 'center',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 12,
  },
  card: {
    height: 160,
    borderRadius: 12,
    overflow: 'hidden',
  },
  flipCard: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  cardFace: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 12,
    overflow: 'hidden',
    backfaceVisibility: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(157,171,155,0.30)',
  },
  cardFaceFill: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: 'rgba(157,171,155,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(157,171,155,0.28)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  cardIconWrapDisabled: {
    backgroundColor: 'rgba(45,45,45,0.08)',
    borderColor: 'rgba(45,45,45,0.16)',
  },
  cardFaceFillDisabled: {
    borderColor: 'rgba(45,45,45,0.2)',
  },
  cardDisabled: {
    opacity: 0.42,
  },
  cardPressed: {
    transform: [{ scale: 0.98 }],
  },
  cardLabel: {
    textAlign: 'center',
    color: ONBOARDING_TOKENS.charcoal,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '700',
    marginBottom: 8,
  },
  cardDescription: {
    textAlign: 'center',
    color: ONBOARDING_TOKENS.charcoal60,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
  },
  selectedIconWrap: {
    width: 62,
    height: 62,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  selectedCheck: {
    width: 24,
    height: 24,
    borderRadius: 999,
    backgroundColor: ONBOARDING_TOKENS.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
