import type { BadgeMappingItem } from './types';

export const COMMUNITY_BADGES: Record<string, BadgeMappingItem> = {
  community_early_birdie: {
    id: 'community_early_birdie',
    name: 'Early Birdie',
    description: 'You were here before it was cool.',
    howToEarn: 'Join in the first 90 days of launch.',
    ionicon: 'sunny-outline',
    imageKey: '033',
    badgeGroup: 'community',
  },
  community_community_helper: {
    id: 'community_community_helper',
    name: 'Community Helper',
    description: 'Putting others first.',
    howToEarn: 'Receive 50 helpful votes.',
    ionicon: 'hand-left-outline',
    imageKey: '034',
    badgeGroup: 'community',
  },
  community_trend_starter: {
    id: 'community_trend_starter',
    name: 'Trend Starter',
    description: 'Always one step ahead of the crowd.',
    howToEarn: 'Be the first to review 5 businesses.',
    ionicon: 'trending-up-outline',
    imageKey: '035',
    badgeGroup: 'community',
  },
  community_columbus: {
    id: 'community_columbus',
    name: 'Columbus',
    description: 'A born explorer of the unknown.',
    howToEarn: 'Be the first to review 10 businesses.',
    ionicon: 'compass-outline',
    imageKey: '020',
    badgeGroup: 'community',
  },
  community_loyal_one: {
    id: 'community_loyal_one',
    name: 'The Loyal One',
    description: 'Consistency is your superpower.',
    howToEarn: 'Review for 6 consecutive months.',
    ionicon: 'repeat-outline',
    imageKey: '037',
    badgeGroup: 'community',
  },
  community_neighbourhood_plug: {
    id: 'community_neighbourhood_plug',
    name: 'Neighbourhood Plug',
    description: 'The go-to person for local recs.',
    howToEarn: 'Receive 100 helpful votes.',
    ionicon: 'location-outline',
    imageKey: '007',
    badgeGroup: 'community',
  },
  community_hidden_gem_hunter: {
    id: 'community_hidden_gem_hunter',
    name: 'Hidden Gem Hunter',
    description: 'Finding magic where others overlook it.',
    howToEarn: 'Discover and review 10 under-reviewed businesses.',
    ionicon: 'diamond-outline',
    imageKey: '039',
    badgeGroup: 'community',
  },
  community_lens_legend: {
    id: 'community_lens_legend',
    name: 'Lens Legend',
    description: 'Your photography elevates every review.',
    howToEarn: 'Add 50 photos across your reviews.',
    ionicon: 'aperture-outline',
    imageKey: '040',
    badgeGroup: 'community',
  },
  community_off_the_grid: {
    id: 'community_off_the_grid',
    name: 'Off the Grid',
    description: 'Shining a light on businesses the internet forgot.',
    howToEarn: 'Review 5 businesses with no prior online reviews.',
    ionicon: 'wifi-outline',
    imageKey: '041',
    badgeGroup: 'community',
  },
  community_plug_of_year: {
    id: 'community_plug_of_year',
    name: 'Plug of the Year',
    description: 'The community voted, you won.',
    howToEarn: 'Be recognised as a top contributor for the year.',
    ionicon: 'medal-outline',
    imageKey: '038',
    badgeGroup: 'community',
  },
};
