import type { BadgeMappingItem } from './types';

export const MILESTONE_BADGES: Record<string, BadgeMappingItem> = {
  milestone_new_voice: {
    id: 'milestone_new_voice',
    name: 'New Voice',
    description: 'Your journey begins with a single review.',
    howToEarn: 'Write your first review.',
    ionicon: 'mic-outline',
    imageKey: '023',
    badgeGroup: 'milestone',
  },
  milestone_rookie_reviewer: {
    id: 'milestone_rookie_reviewer',
    name: 'Rookie Reviewer',
    description: "Five reviews in — you're on a roll.",
    howToEarn: 'Write 5 reviews.',
    ionicon: 'trending-up-outline',
    imageKey: '024',
    badgeGroup: 'milestone',
  },
  milestone_level_up: {
    id: 'milestone_level_up',
    name: 'Level Up!',
    description: 'Ten reviews strong.',
    howToEarn: 'Write 10 reviews.',
    ionicon: 'bar-chart-outline',
    imageKey: '025',
    badgeGroup: 'milestone',
  },
  milestone_review_machine: {
    id: 'milestone_review_machine',
    name: 'Review Machine',
    description: 'Twenty-five reviews and still going.',
    howToEarn: 'Write 25 reviews.',
    ionicon: 'cog-outline',
    imageKey: '026',
    badgeGroup: 'milestone',
  },
  milestone_century_club: {
    id: 'milestone_century_club',
    name: 'Century Club',
    description: '100 reviews. An absolute legend.',
    howToEarn: 'Write 100 reviews.',
    ionicon: 'trophy-outline',
    imageKey: '027',
    badgeGroup: 'milestone',
  },
  milestone_picture_pioneer: {
    id: 'milestone_picture_pioneer',
    name: 'Picture Pioneer',
    description: 'A picture is worth a thousand words.',
    howToEarn: 'Add photos to 5 reviews.',
    ionicon: 'phone-portrait-outline',
    imageKey: '028',
    badgeGroup: 'milestone',
  },
  milestone_snapshot_superstar: {
    id: 'milestone_snapshot_superstar',
    name: 'Snapshot Superstar',
    description: 'Your photos help others choose.',
    howToEarn: 'Add photos to 25 reviews.',
    ionicon: 'camera-outline',
    imageKey: '029',
    badgeGroup: 'milestone',
  },
  milestone_helpful_honeybee: {
    id: 'milestone_helpful_honeybee',
    name: 'Helpful Honeybee',
    description: 'Your reviews are genuinely useful.',
    howToEarn: 'Receive 10 helpful votes.',
    ionicon: 'thumbs-up-outline',
    imageKey: '030',
    badgeGroup: 'milestone',
  },
  milestone_consistency_star: {
    id: 'milestone_consistency_star',
    name: 'Consistency Star',
    description: 'Showing up regularly for the community.',
    howToEarn: 'Write reviews in 3 consecutive months.',
    ionicon: 'star-outline',
    imageKey: '031',
    badgeGroup: 'milestone',
  },
  milestone_streak_spark: {
    id: 'milestone_streak_spark',
    name: 'Streak Spark',
    description: 'The fire is real.',
    howToEarn: 'Write reviews for 7 consecutive days.',
    ionicon: 'flash-outline',
    imageKey: '032',
    badgeGroup: 'milestone',
  },
};
