import type { BadgeMappingItem } from './types';

export const SPECIALIST_OUTDOORS_BADGES: Record<string, BadgeMappingItem> = {
  specialist_outdoors_nature_nomad: {
    id: 'specialist_outdoors_nature_nomad',
    name: 'Nature Nomad',
    description: 'At home in the great outdoors.',
    howToEarn: 'Write 3 outdoors & adventure reviews.',
    ionicon: 'leaf-outline',
    imageKey: '065',
    badgeGroup: 'specialist',
    categoryKey: 'outdoors-adventure',
  },
  specialist_outdoors_thrill_seeker: {
    id: 'specialist_outdoors_thrill_seeker',
    name: 'Thrill Seeker',
    description: 'Adrenaline is your love language.',
    howToEarn: 'Write 10 outdoors & adventure reviews.',
    ionicon: 'trending-up-outline',
    imageKey: '066',
    badgeGroup: 'specialist',
    categoryKey: 'outdoors-adventure',
  },
  specialist_outdoors_adventure_voyager: {
    id: 'specialist_outdoors_adventure_voyager',
    name: 'Adventure Voyager',
    description: 'Always chasing the next great experience.',
    howToEarn: 'Write 25 outdoors & adventure reviews.',
    ionicon: 'navigate-outline',
    imageKey: '067',
    badgeGroup: 'specialist',
    categoryKey: 'outdoors-adventure',
  },
  specialist_outdoors_trail_tamer: {
    id: 'specialist_outdoors_trail_tamer',
    name: 'Trail Tamer',
    description: 'No trail is too tough.',
    howToEarn: 'Write 5 hiking or trail reviews.',
    ionicon: 'map-outline',
    imageKey: '068',
    badgeGroup: 'specialist',
    categoryKey: 'outdoors-adventure',
  },
  specialist_outdoors_beach_bum: {
    id: 'specialist_outdoors_beach_bum',
    name: 'Beach Bum',
    description: 'Sand, sun, and honest reviews.',
    howToEarn: 'Write 5 beach or waterfront reviews.',
    ionicon: 'water-outline',
    imageKey: '069',
    badgeGroup: 'specialist',
    categoryKey: 'outdoors-adventure',
  },
  specialist_outdoors_botanical_buff: {
    id: 'specialist_outdoors_botanical_buff',
    name: 'Botanical Buff',
    description: 'Plants, parks, and fresh air.',
    howToEarn: 'Write 5 garden or park reviews.',
    ionicon: 'flower-outline',
    imageKey: '070',
    badgeGroup: 'specialist',
    categoryKey: 'outdoors-adventure',
  },
  specialist_outdoors_daredevil: {
    id: 'specialist_outdoors_daredevil',
    name: 'Daredevil',
    description: 'Fear is not in your vocabulary.',
    howToEarn: 'Write 5 extreme sports reviews.',
    ionicon: 'flame-outline',
    imageKey: '071',
    badgeGroup: 'specialist',
    categoryKey: 'outdoors-adventure',
  },
};

export const SPECIALIST_SHOPPING_BADGES: Record<string, BadgeMappingItem> = {
  specialist_shopping_retail_royalty: {
    id: 'specialist_shopping_retail_royalty',
    name: 'Retail Royalty',
    description: 'Shopping is an art form.',
    howToEarn: 'Write 3 shopping & lifestyle reviews.',
    ionicon: 'bag-outline',
    imageKey: '072',
    badgeGroup: 'specialist',
    categoryKey: 'shopping-lifestyle',
  },
  specialist_shopping_shopaholic: {
    id: 'specialist_shopping_shopaholic',
    name: 'Shopaholic',
    description: 'Retail therapy is real therapy.',
    howToEarn: 'Write 10 shopping & lifestyle reviews.',
    ionicon: 'cart-outline',
    imageKey: '073',
    badgeGroup: 'specialist',
    categoryKey: 'shopping-lifestyle',
  },
  specialist_shopping_style_spotter: {
    id: 'specialist_shopping_style_spotter',
    name: 'Style Spotter',
    description: 'Fashion-forward and always on trend.',
    howToEarn: 'Write 5 clothing or accessories reviews.',
    ionicon: 'shirt-outline',
    imageKey: '001',
    badgeGroup: 'specialist',
    categoryKey: 'shopping-lifestyle',
  },
  specialist_shopping_gadget_goblin: {
    id: 'specialist_shopping_gadget_goblin',
    name: 'Gadget Goblin',
    description: 'You love tech more than most people.',
    howToEarn: 'Write 5 electronics or tech reviews.',
    ionicon: 'phone-portrait-outline',
    imageKey: '002',
    badgeGroup: 'specialist',
    categoryKey: 'shopping-lifestyle',
  },
  specialist_shopping_baddie_on_budget: {
    id: 'specialist_shopping_baddie_on_budget',
    name: 'Baddie on a Budget',
    description: 'Looking good without breaking the bank.',
    howToEarn: 'Write 5 value-for-money reviews.',
    ionicon: 'wallet-outline',
    imageKey: '003',
    badgeGroup: 'specialist',
    categoryKey: 'shopping-lifestyle',
  },
};
