import type { BadgeMappingItem } from './types';

export const SPECIALIST_FOOD_BADGES: Record<string, BadgeMappingItem> = {
  specialist_food_taste_tester: {
    id: 'specialist_food_taste_tester',
    name: 'Taste Tester',
    description: 'Your palate is always ready.',
    howToEarn: 'Write 3 food & drink reviews.',
    ionicon: 'restaurant-outline',
    imageKey: '047',
    badgeGroup: 'specialist',
    categoryKey: 'food-drink',
  },
  specialist_food_flavour_finder: {
    id: 'specialist_food_flavour_finder',
    name: 'Flavour Finder',
    description: 'Discovering hidden culinary gems.',
    howToEarn: 'Write 10 food & drink reviews.',
    ionicon: 'search-outline',
    imageKey: '017',
    badgeGroup: 'specialist',
    categoryKey: 'food-drink',
  },
  specialist_food_foodie_boss: {
    id: 'specialist_food_foodie_boss',
    name: 'Foodie Boss',
    description: 'The undisputed authority on local dining.',
    howToEarn: 'Write 25 food & drink reviews.',
    ionicon: 'trophy-outline',
    imageKey: '049',
    badgeGroup: 'specialist',
    categoryKey: 'food-drink',
  },
  specialist_food_coffee_connoisseur: {
    id: 'specialist_food_coffee_connoisseur',
    name: 'Coffee Connoisseur',
    description: 'Life runs on good coffee and honest reviews.',
    howToEarn: 'Write 5 café or coffee shop reviews.',
    ionicon: 'cafe-outline',
    imageKey: '050',
    badgeGroup: 'specialist',
    categoryKey: 'food-drink',
  },
  specialist_food_dessert_detective: {
    id: 'specialist_food_dessert_detective',
    name: 'Dessert Detective',
    description: 'Always on the hunt for the perfect sweet treat.',
    howToEarn: 'Write 5 dessert or bakery reviews.',
    ionicon: 'ice-cream-outline',
    imageKey: '042',
    badgeGroup: 'specialist',
    categoryKey: 'food-drink',
  },
  specialist_food_brunch_enthusiast: {
    id: 'specialist_food_brunch_enthusiast',
    name: 'Brunch Enthusiast',
    description: 'Weekend mornings are sacred.',
    howToEarn: 'Write 5 brunch spot reviews.',
    ionicon: 'sunny-outline',
    imageKey: '052',
    badgeGroup: 'specialist',
    categoryKey: 'food-drink',
  },
};
