import type { BadgeMappingItem } from './types';

export const SPECIALIST_BEAUTY_BADGES: Record<string, BadgeMappingItem> = {
  specialist_beauty_glow_getter: {
    id: 'specialist_beauty_glow_getter',
    name: 'Glow Getter',
    description: 'Always finding the best beauty spots.',
    howToEarn: 'Write 3 beauty & wellness reviews.',
    ionicon: 'sparkles-outline',
    imageKey: '053',
    badgeGroup: 'specialist',
    categoryKey: 'beauty-wellness',
  },
  specialist_beauty_self_care_superstar: {
    id: 'specialist_beauty_self_care_superstar',
    name: 'Self-Care Superstar',
    description: 'Self-care is a priority, and you lead by example.',
    howToEarn: 'Write 10 beauty & wellness reviews.',
    ionicon: 'heart-outline',
    imageKey: '054',
    badgeGroup: 'specialist',
    categoryKey: 'beauty-wellness',
  },
  specialist_beauty_beauty_boss: {
    id: 'specialist_beauty_beauty_boss',
    name: 'Beauty Boss',
    description: 'Reigning supreme in the world of beauty.',
    howToEarn: 'Write 25 beauty & wellness reviews.',
    ionicon: 'color-wand-outline',
    imageKey: '055',
    badgeGroup: 'specialist',
    categoryKey: 'beauty-wellness',
  },
  specialist_beauty_cuticle_queen: {
    id: 'specialist_beauty_cuticle_queen',
    name: 'Cuticle Queen',
    description: 'Nails it every single time.',
    howToEarn: 'Write 5 nail salon reviews.',
    ionicon: 'cut-outline',
    imageKey: '056',
    badgeGroup: 'specialist',
    categoryKey: 'beauty-wellness',
  },
  specialist_beauty_mane_lover: {
    id: 'specialist_beauty_mane_lover',
    name: 'Mane Lover',
    description: 'Hair game: always strong.',
    howToEarn: 'Write 5 hair salon reviews.',
    ionicon: 'color-palette-outline',
    imageKey: '057',
    badgeGroup: 'specialist',
    categoryKey: 'beauty-wellness',
  },
  specialist_beauty_serenity_seeker: {
    id: 'specialist_beauty_serenity_seeker',
    name: 'Serenity Seeker',
    description: 'Finding peace one spa review at a time.',
    howToEarn: 'Write 5 spa or wellness reviews.',
    ionicon: 'flower-outline',
    imageKey: '058',
    badgeGroup: 'specialist',
    categoryKey: 'beauty-wellness',
  },
};

export const SPECIALIST_ARTS_BADGES: Record<string, BadgeMappingItem> = {
  specialist_arts_heritage_hunter: {
    id: 'specialist_arts_heritage_hunter',
    name: 'Heritage Hunter',
    description: 'History and culture excite you.',
    howToEarn: 'Write 3 arts & culture reviews.',
    ionicon: 'business-outline',
    imageKey: '059',
    badgeGroup: 'specialist',
    categoryKey: 'arts-culture',
  },
  specialist_arts_local_lore_seeker: {
    id: 'specialist_arts_local_lore_seeker',
    name: 'Local Lore Seeker',
    description: "You know this city's stories better than anyone.",
    howToEarn: 'Write 10 arts & culture reviews.',
    ionicon: 'book-outline',
    imageKey: '060',
    badgeGroup: 'specialist',
    categoryKey: 'arts-culture',
  },
  specialist_arts_culture_master: {
    id: 'specialist_arts_culture_master',
    name: 'Culture Master',
    description: 'A true connoisseur of the arts.',
    howToEarn: 'Write 25 arts & culture reviews.',
    ionicon: 'school-outline',
    imageKey: '061',
    badgeGroup: 'specialist',
    categoryKey: 'arts-culture',
  },
  specialist_arts_curtain_chaser: {
    id: 'specialist_arts_curtain_chaser',
    name: 'Curtain Chaser',
    description: 'If there is a show, you are there.',
    howToEarn: 'Write 5 theatre or performance reviews.',
    ionicon: 'film-outline',
    imageKey: '014',
    badgeGroup: 'specialist',
    categoryKey: 'arts-culture',
  },
  specialist_arts_canvas_collector: {
    id: 'specialist_arts_canvas_collector',
    name: 'Canvas Collector',
    description: 'Galleries and exhibitions are your happy place.',
    howToEarn: 'Write 5 gallery or museum reviews.',
    ionicon: 'color-palette-outline',
    imageKey: '063',
    badgeGroup: 'specialist',
    categoryKey: 'arts-culture',
  },
  specialist_arts_cinephile: {
    id: 'specialist_arts_cinephile',
    name: 'Cinephile',
    description: 'Two hours in the dark beats everything.',
    howToEarn: 'Write 5 cinema reviews.',
    ionicon: 'videocam-outline',
    imageKey: '064',
    badgeGroup: 'specialist',
    categoryKey: 'arts-culture',
  },
};
