import type { BadgeMappingItem } from './types';

export const SPECIALIST_FAMILY_BADGES: Record<string, BadgeMappingItem> = {
  specialist_family_quality_time_seeker: {
    id: 'specialist_family_quality_time_seeker',
    name: 'Quality Time Seeker',
    description: 'Making every family moment count.',
    howToEarn: 'Write 3 family-friendly reviews.',
    ionicon: 'people-outline',
    imageKey: '004',
    badgeGroup: 'specialist',
    categoryKey: 'family-pets',
  },
  specialist_family_bonding_buff: {
    id: 'specialist_family_bonding_buff',
    name: 'Bonding Buff',
    description: 'Family first, always.',
    howToEarn: 'Write 10 family-friendly reviews.',
    ionicon: 'heart-outline',
    imageKey: '018',
    badgeGroup: 'specialist',
    categoryKey: 'family-pets',
  },
  specialist_family_playtime_pro: {
    id: 'specialist_family_playtime_pro',
    name: 'Playtime Pro',
    description: 'Finding the best spots for kids.',
    howToEarn: 'Write 5 kids or family activity reviews.',
    ionicon: 'game-controller-outline',
    imageKey: '006',
    badgeGroup: 'specialist',
    categoryKey: 'family-pets',
  },
  specialist_family_care_companion: {
    id: 'specialist_family_care_companion',
    name: 'Care Companion',
    description: 'Always there for those who need it.',
    howToEarn: 'Write 5 care service reviews.',
    ionicon: 'heart-outline',
    imageKey: '005',
    badgeGroup: 'specialist',
    categoryKey: 'family-pets',
  },
  specialist_family_play_paws: {
    id: 'specialist_family_play_paws',
    name: 'Play & Paws',
    description: 'Furry friends deserve the best too.',
    howToEarn: 'Write 5 pet-friendly business reviews.',
    ionicon: 'paw-outline',
    imageKey: '009',
    badgeGroup: 'specialist',
    categoryKey: 'family-pets',
  },
  specialist_family_friendly_spaces_finder: {
    id: 'specialist_family_friendly_spaces_finder',
    name: 'Friendly Spaces Finder',
    description: 'Finding welcoming spaces for all.',
    howToEarn: 'Write 5 inclusive or accessible venue reviews.',
    ionicon: 'happy-outline',
    imageKey: '010',
    badgeGroup: 'specialist',
    categoryKey: 'family-pets',
  },
};

export const SPECIALIST_EXPERIENCES_BADGES: Record<string, BadgeMappingItem> = {
  specialist_experiences_memory_maker: {
    id: 'specialist_experiences_memory_maker',
    name: 'Memory Maker',
    description: 'Every outing becomes a story.',
    howToEarn: 'Write 3 experience & entertainment reviews.',
    ionicon: 'sparkles-outline',
    imageKey: '008',
    badgeGroup: 'specialist',
    categoryKey: 'experiences-entertainment',
  },
  specialist_experiences_curiosity_cruiser: {
    id: 'specialist_experiences_curiosity_cruiser',
    name: 'Curiosity Cruiser',
    description: 'Always seeking something new.',
    howToEarn: 'Write 10 experience reviews.',
    ionicon: 'compass-outline',
    imageKey: '051',
    badgeGroup: 'specialist',
    categoryKey: 'experiences-entertainment',
  },
  specialist_experiences_vibe_voyager: {
    id: 'specialist_experiences_vibe_voyager',
    name: 'Vibe Voyager',
    description: 'You can read a room instantly.',
    howToEarn: 'Write 25 experience reviews.',
    ionicon: 'radio-outline',
    imageKey: '043',
    badgeGroup: 'specialist',
    categoryKey: 'experiences-entertainment',
  },
  specialist_experiences_beat_chaser: {
    id: 'specialist_experiences_beat_chaser',
    name: 'Beat Chaser',
    description: 'Always in the front row.',
    howToEarn: 'Write 5 music venue reviews.',
    ionicon: 'musical-notes-outline',
    imageKey: '013',
    badgeGroup: 'specialist',
    categoryKey: 'experiences-entertainment',
  },
  specialist_experiences_show_goer: {
    id: 'specialist_experiences_show_goer',
    name: 'Show Goer',
    description: 'The curtain going up is your favourite sound.',
    howToEarn: 'Write 5 show or event reviews.',
    ionicon: 'ticket-outline',
    imageKey: '062',
    badgeGroup: 'specialist',
    categoryKey: 'experiences-entertainment',
  },
  specialist_experiences_weekend_warrior: {
    id: 'specialist_experiences_weekend_warrior',
    name: 'Weekend Warrior',
    description: 'Friday to Sunday is your kingdom.',
    howToEarn: 'Write 5 weekend event reviews.',
    ionicon: 'calendar-outline',
    imageKey: '015',
    badgeGroup: 'specialist',
    categoryKey: 'experiences-entertainment',
  },
};

export const SPECIALIST_SERVICES_BADGES: Record<string, BadgeMappingItem> = {
  specialist_services_service_scout: {
    id: 'specialist_services_service_scout',
    name: 'Service Scout',
    description: 'Hunting down the best service providers.',
    howToEarn: 'Write 3 professional service reviews.',
    ionicon: 'briefcase-outline',
    imageKey: '019',
    badgeGroup: 'specialist',
    categoryKey: 'professional-services',
  },
  specialist_services_solution_seeker: {
    id: 'specialist_services_solution_seeker',
    name: 'Solution Seeker',
    description: 'No problem is unsolvable with the right service.',
    howToEarn: 'Write 10 professional service reviews.',
    ionicon: 'bulb-outline',
    imageKey: '048',
    badgeGroup: 'specialist',
    categoryKey: 'professional-services',
  },
  specialist_services_service_pro: {
    id: 'specialist_services_service_pro',
    name: 'Service Pro',
    description: 'You know great service when you see it.',
    howToEarn: 'Write 25 professional service reviews.',
    ionicon: 'ribbon-outline',
    imageKey: '012',
    badgeGroup: 'specialist',
    categoryKey: 'professional-services',
  },
  specialist_services_fix_it_fairy: {
    id: 'specialist_services_fix_it_fairy',
    name: 'Fix-It Fairy',
    description: 'You always find someone who can sort it out.',
    howToEarn: 'Write 5 repair or trade service reviews.',
    ionicon: 'construct-outline',
    imageKey: '016',
    badgeGroup: 'specialist',
    categoryKey: 'professional-services',
  },
  specialist_services_money_minded: {
    id: 'specialist_services_money_minded',
    name: 'Money-Minded',
    description: 'Finance and value go hand in hand.',
    howToEarn: 'Write 5 financial service reviews.',
    ionicon: 'cash-outline',
    imageKey: '021',
    badgeGroup: 'specialist',
    categoryKey: 'professional-services',
  },
  specialist_services_home_helper: {
    id: 'specialist_services_home_helper',
    name: 'Home Helper',
    description: 'Your home is always in good hands.',
    howToEarn: 'Write 5 home service reviews.',
    ionicon: 'home-outline',
    imageKey: '022',
    badgeGroup: 'specialist',
    categoryKey: 'professional-services',
  },
};
