import { StyleSheet } from 'react-native';
import { CARD_SHADOW_MD } from '../../styles/overlayShadow';
import { businessDetailColors, businessDetailSpacing } from './styles';

export const styles = StyleSheet.create({
  card: {
    borderRadius: businessDetailSpacing.cardRadius,
    borderWidth: 1,
    borderColor: businessDetailColors.borderSoft,
    backgroundColor: businessDetailColors.cardTint,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 10,
    ...CARD_SHADOW_MD,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconPill: {
    width: 32,
    height: 32,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(229,224,229,0.75)',
  },
  heading: {
    color: businessDetailColors.charcoal,
    fontSize: 19,
    fontWeight: '700',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 6,
  },
  headerAction: {
    width: 32,
    height: 32,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(229,224,229,0.75)',
  },
  distanceLoading: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  distancePillSkeletonShort: {
    width: 76,
    height: 26,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.45)',
  },
  distancePillSkeletonMedium: {
    width: 98,
    height: 26,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.45)',
  },
  pillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(255,255,255,0.55)',
    borderWidth: 1,
    borderColor: 'rgba(45,45,45,0.08)',
  },
  pillText: {
    color: businessDetailColors.charcoal,
    fontSize: 12,
    fontWeight: '600',
  },
  locationLabel: {
    color: businessDetailColors.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  mapPreviewWrap: {
    width: '100%',
    height: 220,
    borderRadius: 10,
    overflow: 'hidden',
  },
  mapPreview: {
    width: '100%',
    height: '100%',
  },
  mapOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(17,24,39,0.16)',
  },
  mapOverlayPill: {
    borderRadius: 999,
    backgroundColor: 'rgba(229,224,229,0.92)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  mapOverlayText: {
    color: businessDetailColors.charcoal,
    fontSize: 12,
    fontWeight: '700',
  },
  mapFallback: {
    width: '100%',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 160,
    paddingHorizontal: 16,
  },
  mapFallbackText: {
    color: businessDetailColors.textMuted,
    fontSize: 13,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  actionPrimary: {
    flex: 1,
    borderRadius: 999,
    backgroundColor: businessDetailColors.coral,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  actionPrimaryText: {
    color: businessDetailColors.white,
    fontSize: 13,
    fontWeight: '700',
  },
  actionCircle: {
    width: 40,
    height: 40,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(229,224,229,0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.36)',
  },
  uberButton: {
    borderRadius: 999,
    backgroundColor: 'rgba(229,224,229,0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.36)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 11,
  },
  uberButtonText: {
    color: businessDetailColors.charcoal,
    fontSize: 13,
    fontWeight: '700',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(17,24,39,0.92)',
    justifyContent: 'flex-end',
  },
  modalShell: {
    width: '100%',
    height: '94%',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#121826',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
  },
  modalTitle: {
    color: businessDetailColors.white,
    fontSize: 18,
    fontWeight: '700',
  },
  modalSubtitle: {
    color: 'rgba(255,255,255,0.72)',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 3,
  },
  modalClose: {
    width: 36,
    height: 36,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  modalMap: {
    flex: 1,
  },
  modalMapFallback: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.16)',
    backgroundColor: 'rgba(9,12,19,0.95)',
  },
  modalActionPrimary: {
    flex: 1,
    borderRadius: 999,
    backgroundColor: businessDetailColors.coral,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  modalActionPrimaryText: {
    color: businessDetailColors.white,
    fontSize: 13,
    fontWeight: '700',
  },
  modalActionSecondary: {
    flex: 1,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.18)',
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  modalActionSecondaryText: {
    color: businessDetailColors.white,
    fontSize: 13,
    fontWeight: '700',
  },
  modalShare: {
    width: 44,
    height: 44,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
});
