import { StyleSheet } from 'react-native';
import { NAVBAR_BG_COLOR } from '../../styles/colors';

export const C = {
  offWhite: '#E5E0E5',
  charcoal: '#2D2D2D',
  sage: '#7D9B76',
  coral: NAVBAR_BG_COLOR,
  white: '#FFFFFF',
  charcoal60: 'rgba(45,45,45,0.60)',
  charcoal45: 'rgba(45,45,45,0.45)',
  charcoal40: 'rgba(45,45,45,0.40)',
  charcoal30: 'rgba(45,45,45,0.30)',
  amber: '#F5D547',
  amberDark: '#E6A547',
  sageBorder: 'rgba(125,155,118,0.10)',
  offWhiteBg: 'rgba(229,224,229,0.95)',
};

export const styles = StyleSheet.create({
  card: {
    borderRadius: 8,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  } as object,
  row: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  avatarWrap: { flexShrink: 0 },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.40)',
  },
  avatarFallback: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: C.offWhite,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.40)',
  },
  avatarInitial: { fontSize: 18, fontWeight: '700', color: C.sage },
  content: { flex: 1, gap: 8 },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  headerLeft: { flex: 1, minWidth: 0 },
  nameRow: { flexDirection: 'row', alignItems: 'center', gap: 4, flexWrap: 'wrap' },
  name: { fontSize: 18, fontWeight: '600', color: C.charcoal, flexShrink: 1 },
  anonPill: {
    borderRadius: 999,
    backgroundColor: 'rgba(45,45,45,0.12)',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  anonText: { fontSize: 11, fontWeight: '600', color: C.charcoal60 },
  headerRight: { alignItems: 'flex-end', gap: 4, flexShrink: 0 },
  starsRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  starFilledWrap: {
    width: 20,
    height: 20,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noRatingPill: {
    borderRadius: 999,
    backgroundColor: 'rgba(45,45,45,0.08)',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  noRatingText: { fontSize: 11, fontWeight: '600', color: C.charcoal45 },
  date: { fontSize: 12, fontWeight: '600', color: C.charcoal45 },
  title: { fontSize: 20, fontWeight: '600', color: C.charcoal },
  body: { fontSize: 16, fontWeight: '600', color: 'rgba(45,45,45,0.90)', lineHeight: 24 },
  readMoreText: { fontSize: 13, fontWeight: '600', color: C.sage, marginTop: -4 },
  verifiedRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  verifiedText: { fontSize: 10, fontWeight: '600', color: 'rgba(45,45,45,0.60)' },
  tagsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  tagPill: {
    borderRadius: 999,
    backgroundColor: C.coral,
    borderWidth: 1,
    borderColor: 'rgba(45,45,45,0.10)',
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  tagText: { fontSize: 13, fontWeight: '600', color: C.offWhite },
  imagesScroll: { marginTop: 4 },
  imagesContent: { gap: 8 },
  reviewImage: { width: 120, height: 80, borderRadius: 8 },
  reviewImageError: {
    backgroundColor: 'rgba(45,45,45,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(125,155,118,0.10)',
    gap: 12,
  },
  helpfulBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
  },
  helpfulBtnActive: { backgroundColor: 'rgba(125,155,118,0.10)' },
  helpfulBtnGuest: { opacity: 0.45 },
  helpfulText: { fontSize: 13, fontWeight: '500', color: C.charcoal45 },
  helpfulTextActive: { color: C.sage },
  helpfulTextGuest: { color: C.charcoal30 },
  lightboxOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lightboxImage: { width: '100%', height: '80%' },
  lightboxClose: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
