import { StyleSheet } from 'react-native';
import { APP_PAGE_GUTTER } from '../../../styles/layout';
import { CARD_SHADOW_MD } from '../../../styles/overlayShadow';
import { OFF_WHITE, CARD_BG, CHARCOAL } from './savedScreenTokens';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: OFF_WHITE },
  scroll: { flex: 1 },
  scrollContent: { paddingBottom: 24 },
  maxContainer: {
    width: '100%',
    maxWidth: 2000,
    alignSelf: 'center',
    paddingHorizontal: APP_PAGE_GUTTER,
  },

  titleSection: { paddingHorizontal: APP_PAGE_GUTTER },
  titleHeading: { color: CHARCOAL, fontWeight: '800', letterSpacing: -0.35 },
  titleSubtitle: {
    marginTop: 8,
    fontSize: 16,
    lineHeight: 24,
    color: 'rgba(45,45,45,0.6)',
    fontWeight: '500',
  },

  filterWrap: { marginBottom: 24, paddingHorizontal: APP_PAGE_GUTTER },
  pillScroll: { maxHeight: 42 },
  pillRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    borderRadius: 999,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: 'rgba(45,45,45,0.12)',
    backgroundColor: 'rgba(255,255,255,0.6)',
  },
  pillActive: { borderColor: 'rgba(157,171,155,0.5)', backgroundColor: 'rgba(157,171,155,0.92)' },
  pillPressed: { opacity: 0.92 },
  pillText: { color: 'rgba(45,45,45,0.7)', fontWeight: '600' },
  pillCount: { color: 'rgba(45,45,45,0.6)', fontWeight: '600' },
  pillTextActive: { color: '#FFFFFF' },

  gridWrap: { width: '100%' },
  gridRow: { flexDirection: 'row', alignItems: 'stretch' },
  gridCell: { flex: 1, minWidth: 0 },

  filteredEmptyWrap: { alignItems: 'center', justifyContent: 'center', paddingVertical: 48 },
  filteredEmptyIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(229,224,229,0.7)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filteredEmptyText: {
    marginTop: 10,
    fontSize: 18,
    lineHeight: 28,
    color: 'rgba(45,45,45,0.6)',
    textAlign: 'center',
    fontWeight: '500',
  },
  exploreButton: {
    marginTop: 16,
    paddingHorizontal: 24,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: CARD_BG,
  },
  exploreButtonText: { fontSize: 14, color: '#FFFFFF', fontWeight: '600' },

  paginationWrap: { marginTop: 32 },
  paginationRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  paginationNavButton: { width: 40, height: 40, borderRadius: 20, overflow: 'hidden' },
  paginationNavButtonEnabled: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  paginationNavButtonDisabled: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: 'rgba(229,224,229,0.5)',
  },
  paginationNumbersRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  paginationEllipsis: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    color: 'rgba(45,45,45,0.7)',
    fontWeight: '500',
  },
  paginationPageButton: { minWidth: 40, height: 40, borderRadius: 999, overflow: 'hidden' },
  paginationPageGradient: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  paginationPageText: { fontSize: 14, fontWeight: '600', color: CHARCOAL },
  paginationPageTextActive: { color: '#FFFFFF' },

  errorWrap: {
    minHeight: 360,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  errorInner: { width: '100%', maxWidth: 420, alignItems: 'center' },
  errorText: {
    marginBottom: 16,
    textAlign: 'center',
    fontSize: 18,
    lineHeight: 28,
    color: 'rgba(45,45,45,0.7)',
  },
  retryButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: CARD_BG,
  },
  retryButtonText: { color: '#FFFFFF', fontSize: 18, fontWeight: '700' },

  emptyStatePad: { paddingHorizontal: APP_PAGE_GUTTER },
  emptyStateWrap: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 80,
  },
  emptyStateIconWrap: {
    width: 64,
    height: 64,
    marginBottom: 16,
    borderRadius: 999,
    backgroundColor: 'rgba(45,45,45,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyStateTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: 'rgba(45,45,45,0.5)',
    textAlign: 'center',
  },
  emptyStateSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: 'rgba(45,45,45,0.38)',
    textAlign: 'center',
  },

  skeletonHeaderWrap: { marginBottom: 24, paddingHorizontal: APP_PAGE_GUTTER },
  skeletonHeadingBar: {
    height: 36,
    width: 224,
    borderRadius: 12,
    backgroundColor: 'rgba(45,45,45,0.10)',
  },
  skeletonSubtitleBar: {
    marginTop: 12,
    height: 16,
    width: 160,
    borderRadius: 8,
    backgroundColor: 'rgba(45,45,45,0.10)',
  },
  skeletonPillWrap: { marginBottom: 24, paddingHorizontal: APP_PAGE_GUTTER },
  skeletonPillRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  skeletonPillSmall: {
    width: 64,
    height: 32,
    borderRadius: 999,
    backgroundColor: 'rgba(45,45,45,0.10)',
  },
  skeletonPillMedium: {
    width: 80,
    height: 32,
    borderRadius: 999,
    backgroundColor: 'rgba(45,45,45,0.10)',
  },
  skeletonPillLarge: {
    width: 96,
    height: 32,
    borderRadius: 999,
    backgroundColor: 'rgba(45,45,45,0.10)',
  },
  skeletonCard: {
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: CARD_BG,
    ...CARD_SHADOW_MD,
  },
  skeletonCardMedia: { width: '100%', height: 220, backgroundColor: 'rgba(157,171,155,0.95)' },
  skeletonCardBody: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 14,
    alignItems: 'center',
    backgroundColor: 'rgba(157,171,155,0.32)',
  },
  skeletonCardTitle: {
    height: 24,
    borderRadius: 10,
    width: '72%',
    backgroundColor: 'rgba(45,45,45,0.10)',
  },
  skeletonCardSubtitle: {
    marginTop: 10,
    height: 13,
    borderRadius: 7,
    width: '48%',
    backgroundColor: 'rgba(45,45,45,0.08)',
  },
  skeletonCardReview: {
    marginTop: 9,
    height: 12,
    borderRadius: 6,
    width: '38%',
    backgroundColor: 'rgba(45,45,45,0.08)',
  },
  skeletonCardPillRow: {
    marginTop: 12,
    height: 28,
    borderRadius: 14,
    width: '92%',
    backgroundColor: 'rgba(229,224,229,0.55)',
  },

  paginationOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 9998,
    backgroundColor: 'rgba(229,224,229,0.92)',
  },
  paginationOverlayInner: { paddingTop: 96, paddingBottom: 40, flex: 1 },
});
